BLAIS5-3671: exclude "unexpected end of JSON input" logs
ONSdigital/blaise-slack-alerter pull request #66
Opened 2023-03-20 10:35 UTC by Enigma-cloud

2023-03-22 12:20 UTC, tomphp requested changes

2023-03-22 12:20 UTC, tomphp commented on lib/filters/osconfig_agent_filter.py
> +    if log_entry.platform == "gce_instance":
A [guard class](https://refactoring.guru/replace-nested-conditional-with-guard-clauses) could be used here to remove the nesting.

2023-03-22 12:20 UTC, tomphp commented on lib/send_alerts.py
> +    print(log_entry)
This looks like a debug `print`, can it be removed?

2023-03-22 12:20 UTC, tomphp commented on tests/lib/filters/test_osconfig_agent_filter.py
> +def mock_log_entry(
A more idiomatic approach would be to make this a `@pytest.fixture()`.
You could then use `dataclass.replace` to update values for each test.

See [this test](https://github.com/ONSdigital/blaise-slack-alerter/blob/main/tests/lib/log_processor/log_types/test_gce_instance.py#L39) for an example.

2023-03-23 11:10 UTC, JAWilliamsONS approved these changes
Gone through with Kris in person - looks really good and happy to approve
Obviously can't test in the real world so will merge and monitor if these alerts still come through
Unit tests are in place though 👍

2023-03-23 11:11 UTC, JAWilliamsONS approved these changes
changes made by Kris

2023-03-23 11:13 UTC, merged